# Generated by Django 2.0.6 on 2018-06-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhumansmember',
            name='oh_username',
            field=models.CharField(default='user', max_length=256),
        ),
    ]
