language: python

services:


python:
    - "3.5"
    - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - mkdir bin
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > bin/cc-test-reporter
  - chmod +x bin/cc-test-reporter
  - bin/cc-test-reporter before-build

script:
  - coverage run --source="." manage.py test

after_success:
  - coverage xml
  - bin/cc-test-reporter after-build -t coverage.py
