# Generated by Django 2.0.5 on 2018-05-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNotebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default='2018-05-24 17:08:29+00:00')),
                ('last_submitted', models.DateTimeField(default='2018-05-24 17:08:29+00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.OpenHumansMember')),
            ],
        ),
    ]
