# Generated by Django 2.0.5 on 2018-05-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharednotebook',
            old_name='user',
            new_name='oh_member',
        ),
        migrations.RemoveField(
            model_name='sharednotebook',
            name='last_submitted',
        ),
        migrations.RemoveField(
            model_name='sharednotebook',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2018-05-24 20:59:01+00:00'),
        ),
        migrations.AddField(
            model_name='sharednotebook',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sharednotebook',
            name='notebook_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sharednotebook',
            name='notebook_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sharednotebook',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2018-05-24 20:59:01+00:00'),
        ),
    ]
