# Generated by Django 2.0.5 on 2018-05-31 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180531_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2018-05-24 21:08:24+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='oh_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_humans.OpenHumansMember'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2018-05-24 21:08:24+00:00'),
        ),
    ]
