# Generated by Django 2.0.6 on 2018-06-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180601_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2018-05-27 04:49:28+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2018-05-27 04:49:28+00:00'),
        ),
    ]
