# Generated by Django 2.0.6 on 2018-06-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0002_openhumansmember_oh_username'),
        ('main', '0005_auto_20180603_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='')),
                ('created_at', models.DateTimeField(default='2018-06-03 04:53:38+00:00')),
            ],
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2018-05-27 04:53:38+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2018-05-27 04:53:38+00:00'),
        ),
        migrations.AddField(
            model_name='notebookcomment',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SharedNotebook'),
        ),
        migrations.AddField(
            model_name='notebookcomment',
            name='oh_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_humans.OpenHumansMember'),
        ),
    ]
