# Generated by Django 2.0.6 on 2018-07-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180604_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednotebook',
            name='master_notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SharedNotebook'),
        ),
        migrations.AlterField(
            model_name='notebookcomment',
            name='created_at',
            field=models.DateTimeField(default='2018-07-05 20:06:48+00:00'),
        ),
        migrations.AlterField(
            model_name='notebooklike',
            name='created_at',
            field=models.DateTimeField(default='2018-07-05 20:06:48+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='created_at',
            field=models.DateTimeField(default='2018-06-28 20:06:48+00:00'),
        ),
        migrations.AlterField(
            model_name='sharednotebook',
            name='updated_at',
            field=models.DateTimeField(default='2018-06-28 20:06:48+00:00'),
        ),
    ]
